apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ph88cu1tp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ph88cu1tp-go 
  name: ph88cu1tp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ph88cu1tp-go 
